name: Unit Test / Lint

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install deps and build (with cache)
        run: |
          pnpm install

      - name: Lint
        run: |
          pnpm lint
      - name: Test
        run: |
          pnpm test
