name: Unit Test / Lint

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18.12.1'

      - name: Install deps and build (with cache)
        run: |
          npm install -g pnpm
          pnpm install

      - name: Lint
        run: |
          pnpm style:lint
      - name: Test
        run: |
          pnpm test:jest
      - name: TS Check
        run: |
          pnpm ts:check
